### PR TITLE
fix coinbase deserialization

### LINKED ISSUE #1771: bad coinbase deserialization is breaking JD
on #1745 we changed the coinbase serialization/deserialization logic of JDC and JDS, as an adaptation to spec changes of https://github.com/stratum-mining/sv2-spec/pull/138

we started making heavy usage of `roles_logic_sv2::utils::deserialize_outputs`, which turns out to be buggy

this is leading to Pool rejecting shares from JDC, as each side was ending up with different serialized outputs for the custom job (which we're not catching on CI)

we should:
- stop using `roles_logic_sv2::utils::deserialize_outputs` in favor of `Vec::<TxOut>::consensus_decode` (or `TxOut::consensus_decode` for template outputs, see https://github.com/Sjors/bitcoin/issues/92)
- introduce an integration test that validates that we're able to do the full-cycle of JD mining

### PR DESCRIPTION
**Pull request by plebhash**
close #1771

### CODE REVIEW

File: protocols/v2/roles-logic-sv2/src/channels/server/jobs/extended.rs [hunk 1]
```diff
@@ -36,19 +35,38 @@ impl<'a> ExtendedJob<'a> {
...
+        if template_coinbase_outputs.is_empty() {
+            template_coinbase_outputs = vec![TxOut::consensus_decode(
+                &mut template
+                    .coinbase_tx_outputs
+                    .inner_as_ref()
+                    .to_vec()
+                    .as_slice(),
+            )
+            .map_err(|_| ExtendedJobError::FailedToDeserializeCoinbaseOutputs)?];
+        }
```
Comment (plebhash) [inline protocols/v2/roles-logic-sv2/src/channels/server/jobs/extended.rs:58]: we should remove this once https://github.com/Sjors/bitcoin/issues/92 is fixed

File: protocols/v2/roles-logic-sv2/src/channels/server/jobs/standard.rs [hunk 2]
```diff
@@ -23,18 +23,38 @@ impl<'a> StandardJob<'a> {
...
+        if template_coinbase_outputs.is_empty() {
+            template_coinbase_outputs = vec![TxOut::consensus_decode(
+                &mut template
+                    .coinbase_tx_outputs
+                    .inner_as_ref()
+                    .to_vec()
+                    .as_slice(),
+            )
+            .map_err(|_| StandardJobError::FailedToDeserializeCoinbaseOutputs)?];
+        }
```
Comment (plebhash) [inline protocols/v2/roles-logic-sv2/src/channels/server/jobs/standard.rs:46]: we should remove this once https://github.com/Sjors/bitcoin/issues/92 is fixed

File: roles/jd-client/src/lib/job_declarator/mod.rs [hunk 3]
```diff
@@ -418,9 +423,34 @@ impl JobDeclarator {
...
+                                if template_coinbase_outputs.is_empty() {
+                                    template_coinbase_outputs = vec![TxOut::consensus_decode(
+                                        &mut template
+                                            .coinbase_tx_outputs
+                                            .inner_as_ref()
+                                            .to_vec()
+                                            .as_slice(),
+                                    )
+                                    .expect("Failed to deserialize template outputs")];
+                                }
```
Comment (plebhash) [inline roles/jd-client/src/lib/job_declarator/mod.rs:446]: we should remove this once https://github.com/Sjors/bitcoin/issues/92 is fixed

File: roles/jd-client/src/lib/job_declarator/mod.rs [hunk 4]
```diff
@@ -540,8 +570,34 @@ impl JobDeclarator {
...
+            if template_coinbase_outputs.is_empty() {
+                template_coinbase_outputs = vec![TxOut::consensus_decode(
+                    &mut template
+                        .coinbase_tx_outputs
+                        .inner_as_ref()
+                        .to_vec()
+                        .as_slice(),
+                )
+                .expect("Failed to deserialize template outputs")];
+            }
```
Comment (plebhash) [inline roles/jd-client/src/lib/job_declarator/mod.rs:592]: we should remove this once https://github.com/Sjors/bitcoin/issues/92 is fixed

File: protocols/v2/roles-logic-sv2/src/channels/server/jobs/factory.rs [hunk 5]
```diff
@@ -322,19 +327,29 @@ impl JobFactory {
...
+        if template_outputs.is_empty() {
+            template_outputs = vec![TxOut::consensus_decode(
+                &mut template
+                    .coinbase_tx_outputs
+                    .inner_as_ref()
+                    .to_vec()
+                    .as_slice(),
+            )
+            .map_err(|_| JobFactoryError::DeserializeCoinbaseOutputsError)?];
         }
```
Comment (GitGab19) [inline protocols/v2/roles-logic-sv2/src/channels/server/jobs/factory.rs:349]: we should also remove this after https://github.com/Sjors/bitcoin/issues/92 is fixed

**Review by GitGab19 — APPROVED** [review]
