### PR TITLE
Fix timestamp bug - `min_ntime` becomes always the one sent by TP

### LINKED ISSUE #1324: Pool and JDC update `nTime` field with current timestamp - they should use the one sent by TP
Our current Pool and JDC update the `nTime` field of every job using the current system time, instead of using the value sent by TP. This leads to mine invalid blocks when the value is too old with respect to the network one. We were able to notice this bug on `testnet4`, since its MTP is moved in the future.

Here some logs which shows TP logs when this bug is in place:

timestamp-bug

cc @Sjors

### PR DESCRIPTION
**Pull request by GitGab19**
This PR introduces a new `last_ntime` field into `JobsCreators` struct to save the last `nTime` value sent by TP. 

In this way, the correct value is always used when creating new jobs (future and not), instead of using the current system time.

Closes #1324

### CODE REVIEW

**Comment by GitGab19** [comment]
@plebhash @jbesraa do you think we need to add a new integration test for this? We are able to assert specific fields value inside specific messages, right?

Also, let me know if you want me to bump `roles_logic_sv2` patch version here or not.

**Comment by plebhash** [comment]
> do you think we need to add a new integration test for this? 

IMO more tests are always desirable

the real question is how complex it is to write a comprehensive test for this bug

if it is too complex and we decide it's not worth spending our time on it now, we could always take note of this on https://github.com/stratum-mining/stratum/issues/1077 and come back to it later

> We are able to assert specific fields value inside specific messages, right?

yes, see:

https://github.com/stratum-mining/stratum/blob/a58246ab04534f4a665afce9166a5004675118b0/roles/tests-integration/tests/common/sniffer.rs#L465-L470

or a more concrete example:
https://github.com/stratum-mining/stratum/blob/a58246ab04534f4a665afce9166a5004675118b0/roles/tests-integration/tests/pool_integration.rs#L40-L51

> Also, let me know if you want me to bump roles_logic_sv2 patch version here or not.

are we doing a patch release for this bugfix?

if yes, then we should bump and release right away

if not, then we should take note of this change and then bump before v1.3.0 (maybe there will be a MAJOR or MINOR bump that would overwrite this)

**Comment by Sjors** [comment]
You should the `curtime` field, not `mintime`. For the timewarp scenario that this PR fixes, they're the same. But normally `mintime` is equal to MTP + 1, which on mainnet is typically an hour in the past. Whereas `curtime` is the node clock time, adjusted for MTP + 1 and for timewarp where needed.

**Comment by GitGab19** [comment]
> You should the `curtime` field, not `mintime`. For the timewarp scenario that this PR fixes, they're the same. But normally `mintime` is equal to MTP + 1, which on mainnet is typically an hour in the past. Whereas `curtime` is the node clock time, adjusted for MTP + 1 and for timewarp where needed.

I'm not following you here, weren't we saying that we should always use the timestamp communicated by the TP?

**Comment by Sjors** [comment]
Maybe I'm just confused by the name. The `getblocktemplate` RPC has both a `curtime` and `mintime` field. But the TP doesn't use that field and just gives you the `nTime` value in the block. That's _not_ the minimum time, so the variable name `mintime` is confusing. But it should work correctly.

**Comment by GitGab19** [comment]
What I'm using in this PR is the `header_timestamp` field contained in the `SetNewPrevHash` message, as [specified here](https://github.com/stratum-mining/sv2-spec/blob/main/07-Template-Distribution-Protocol.md#73-setnewprevhash-server---client). It's correct, right?

Regarding the naming, do you think something could be optimized in the specs?

**Comment by Sjors** [comment]
Yes, it's indeed `header_timestamp`.

The spec is clear:

> The nTime field in the block header at which the client should start (usually current time). This is NOT the minimum valid nTime value.

Some part of the SRI codebase is calling it `Some(referenced_job.min_ntime)`. I think that variable should be renamed from `min_ntime` to either `ntime` or `header_timestamp`.

File: protocols/v2/roles-logic-sv2/src/job_creator.rs [hunk 1]
```diff
@@ -162,6 +166,7 @@ pub fn extended_job_from_custom_job(
         0,
         true,
         extranonce_len,
+        Some(referenced_job.min_ntime),
```
Comment (Sjors) [inline protocols/v2/roles-logic-sv2/src/job_creator.rs:169]: ^

File: protocols/v2/roles-logic-sv2/src/job_creator.rs [hunk 2]
```diff
@@ -207,13 +213,7 @@ fn new_extended_job(
 
     let min_ntime = match new_template.future_template {
```
Comment (Sjors) [inline protocols/v2/roles-logic-sv2/src/job_creator.rs:214]: ^

**Comment by GitGab19** [comment]
> Yes, it's indeed `header_timestamp`.
> 
> The spec is clear:
> 
> > The nTime field in the block header at which the client should start (usually current time). This is NOT the minimum valid nTime value.
> 
> Some part of the SRI codebase is calling it `Some(referenced_job.min_ntime)`. I think that variable should be renamed from `min_ntime` to either `ntime` or `header_timestamp`.

I think that's because on the mining protocol specs is specified as min_ntime: https://github.com/stratum-mining/sv2-spec/blob/main/05-Mining-Protocol.md#5315-newminingjob-server---client

Don't you think we should enhance that part of the specs? I can push changes on this PR, but I think that if we agree on it, we should also clarify specs.

**Comment by Sjors** [comment]
Yes it makes sense to improve the spec there.

> Smallest nTime value available for hashing for the new mining job. 

There's currently no way to know this, unless we add a new field to the NewTemplate and/or SetNewPrevHash message.

**Comment by GitGab19** [comment]
@Sjors took note of this improvements on both:
- specs (https://github.com/stratum-mining/sv2-spec/issues/119)
- SRI (https://github.com/stratum-mining/stratum/issues/1202#issuecomment-2569489461)

**Comment by GitGab19** [comment]
@plebhash integration test added in e4e5e61a6c1058347c0e9ee12bda8a73b438c4c7.

Wrt version bumping, I would discuss about it during next `dev call`. So that we can better agree on the need about doing a patch release or not.

File: roles/tests-integration/tests/common/mod.rs [hunk 3]
```diff
@@ -284,8 +285,8 @@ pub async fn start_pool(
     pool
 }
 
-pub async fn start_template_provider(tp_port: u16) -> TemplateProvider {
-    let template_provider = TemplateProvider::start(tp_port);
+pub async fn start_template_provider(tp_port: u16, sv2_interval: u32) -> TemplateProvider {
```
Comment (jbesraa) [inline roles/tests-integration/tests/common/mod.rs:288]: Instead of repeating `20` value for tests that don't need to set this, you can set a default `sv2_interval` value here.

`let sv2_interval = sv2_interval.unwrap_or(20)`

File: roles/tests-integration/tests/pool_integration.rs [hunk 4]
```diff
@@ -64,12 +66,128 @@ async fn success_pool_template_provider_connection() {
...
+async fn header_timestamp_value_assertion_in_new_extended_mining_job() {
+    let tp_pool_sniffer_addr = common::get_available_address();
+    let pool_translator_sniffer_addr = common::get_available_address();
+    let tp_addr = common::get_available_address();
+    let pool_addr = common::get_available_address();
+    let sv2_interval = 5;
+    let _tp = common::start_template_provider(tp_addr.port(), sv2_interval).await;
+
+    let tp_pool_sniffer =
+        common::start_sniffer("0".to_string(), tp_pool_sniffer_addr, tp_addr, false, None).await;
```
Comment (jbesraa) [inline roles/tests-integration/tests/pool_integration.rs:93]: Both sniffers have `"0"` as the first argument which is the ID of the sniffer. The ID makes it easier to debug errors in the test, if they occur. 
It would be better to give unique names here.

File: roles/tests-integration/tests/pool_integration.rs [hunk 5]
```diff
@@ -64,12 +66,128 @@ async fn success_pool_template_provider_connection() {
...
+
+    let _ = common::start_pool(Some(pool_addr), Some(tp_pool_sniffer_addr)).await;
+
+    let pool_translator_sniffer = common::start_sniffer(
+        "0".to_string(),
```
Comment (jbesraa) [inline roles/tests-integration/tests/pool_integration.rs:98]: ^

File: roles/tests-integration/tests/pool_integration.rs [hunk 6]
```diff
@@ -64,12 +66,128 @@ async fn success_pool_template_provider_connection() {
...
+        OpenExtendedMiningChannelSuccess
+    );
+    assert_mining_message!(
+        &pool_translator_sniffer.next_message_from_upstream(),
+        NewExtendedMiningJob
+    );
+    assert_mining_message!(
+        &pool_translator_sniffer.next_message_from_upstream(),
+        SetNewPrevHash
+    );
```
Comment (jbesraa) [inline roles/tests-integration/tests/pool_integration.rs:156]: Do we actually need to assert all of this?

**Review by jbesraa — CHANGES_REQUESTED** [review]
It is really great to see you using the integration tests!

Added a few nits mainly in that regard.

File: protocols/v2/roles-logic-sv2/src/job_creator.rs [hunk 7]
```diff
@@ -432,11 +432,11 @@ impl StrippedCoinbaseTx {
...
-        32 // outpoint
-        + 4 // vout
-        + 1 // script length byte -> TODO can be also 3 (based on TODO in `coinbase_tx_prefix()`)
-        + self.bip141_bytes_len // space for bip34 bytes
-        ;
+            32 // outpoint
+                + 4 // vout
+                + 1 // script length byte -> TODO can be also 3 (based on TODO in `coinbase_tx_prefix()`)
+                + self.bip141_bytes_len // space for bip34 bytes
+            ;
```
Comment (plebhash) [inline protocols/v2/roles-logic-sv2/src/job_creator.rs:439]: what's the motivation behind this change?

did it come from `cargo fmt`?

File: roles/tests-integration/tests/pool_integration.rs [hunk 8]
```diff
@@ -64,12 +66,128 @@ async fn success_pool_template_provider_connection() {
...
+//   occurred with non-future jobs.
+//
+// Related issue: https://github.com/stratum-mining/stratum/issues/1324
+#[tokio::test]
+async fn header_timestamp_value_assertion_in_new_extended_mining_job() {
+    let tp_pool_sniffer_addr = common::get_available_address();
+    let pool_translator_sniffer_addr = common::get_available_address();
+    let tp_addr = common::get_available_address();
+    let pool_addr = common::get_available_address();
+    let sv2_interval = 5;
```
[the remark this answers is not in the document]
Comment (GitGab19) [reply roles/tests-integration/tests/pool_integration.rs:89]: I set it to 5s so that a second template (and so a second job) is created in 5s. In this way we avoid to wait for too much time for this test.

File: roles/tests-integration/tests/pool_integration.rs [hunk 9]
```diff
@@ -64,12 +66,128 @@ async fn success_pool_template_provider_connection() {
...
+    assert_mining_message!(
+        &pool_translator_sniffer.next_message_from_upstream(),
+        NewExtendedMiningJob
+    );
+    assert_mining_message!(
+        &pool_translator_sniffer.next_message_from_upstream(),
+        SetNewPrevHash
+    );
+
+    // Wait for a second NewExtendedMiningJob message
```
[the remark this answers is not in the document]
Comment (GitGab19) [reply roles/tests-integration/tests/pool_integration.rs:158]: The focus of the test is on the second job, because the bug described by issue #1324 is manifesting on NON-future jobs. But when you connect a client to TP, TP sends a first future template (followed by its corresponding `SetNewPrevHash`), which becomes a future job sent downstream. After `sv2interval` seconds, a NON-future template is sent from the TP, which becomes a NON-future job sent downstream.

I hope this helps you clarify also the reason behind this comment: https://github.com/stratum-mining/stratum/pull/1325#discussion_r1905214342

File: roles/tests-integration/tests/pool_integration.rs (hunk 6 above)
Comment (GitGab19) [reply roles/tests-integration/tests/pool_integration.rs:156]: No, but I was not able to make it work without asserting (and so popping from the sniffer) all those messages. Any suggestion to avoid them?

File: protocols/v2/roles-logic-sv2/src/job_creator.rs [hunk 10]
```diff
@@ -207,13 +213,7 @@ fn new_extended_job(
...
     let min_ntime = match new_template.future_template {
         true => binary_sv2::Sv2Option::new(None),
-        false => {
-            let now = std::time::SystemTime::now()
-                .duration_since(std::time::UNIX_EPOCH)
-                .unwrap()
-                .as_secs() as u32;
-            binary_sv2::Sv2Option::new(Some(now))
-        }
+        false => binary_sv2::Sv2Option::new(ntime),
```
[the remark this answers is not in the document]
Comment (GitGab19) [reply protocols/v2/roles-logic-sv2/src/job_creator.rs]: Done in b53152c0548cf849ecd4feb7910f32dca9d37164

File: roles/tests-integration/tests/common/mod.rs (hunk 3 above)
Comment (GitGab19) [reply roles/tests-integration/tests/common/mod.rs]: Done in b53152c0548cf849ecd4feb7910f32dca9d37164

File: roles/tests-integration/tests/pool_integration.rs (hunk 4 above)
Comment (GitGab19) [reply roles/tests-integration/tests/pool_integration.rs]: Done in b53152c0548cf849ecd4feb7910f32dca9d37164

File: roles/tests-integration/tests/pool_integration.rs (hunk 6 above)
Comment (GitGab19) [reply roles/tests-integration/tests/pool_integration.rs]: I removed some of them in b53152c0548cf849ecd4feb7910f32dca9d37164

**Comment by plebhash** [comment]
I did some local manual testing for the semver issue:
- make sure `cargo semver-checks` is 0.37.0 (same as CI)
- `cd protocols/v2/roles-logic-sv2; cargo +stable semver-checks --default-features`

no errors were reported

it's very good that @Shourya742 had the eagle eyes to detect this potential versioning issue, but we should definitely investigate deeper to know if:
- @Shourya742 was mistaken and a PATCH bump is sufficient
- OR we need to fix the CI, as it's not reliable

**Comment by plebhash** [comment]
for future reference:

after some investigation, it was confirmed that the semver issue was a false alarm

although the `JobsCreators` is a public struct, the added field is private, which therefore does not categorize a MAJOR version bump

**Review by plebhash — APPROVED** [review]
