### PR TITLE
Minor warning and error grammar and typo fixes

### LINKED ISSUE #1280: misleading JDC logs need to be refactored
While testing I've found a few possibly typos or grammatical errors:

Before anyone tries to resolve them, developer on the project needs to confirm my interpretation is correct.

1. `2024-12-09T18:17:08.807208Z ERROR roles_logic_sv2::channel_logic::channel_factory: Share does not meet any target: Extended(SubmitSharesExtended { channel_id: 5, sequence_number: 0, job_id: 22, nonce: 258540344, ntime: 1733768213, version: 551460864, extranonce: Owned([0, 0, 0, 0, 0, 0, 0, 1, 255, 2, 0, 0, 0, 0, 0, 0]) })
2024-12-09T18:17:08.812152Z ERROR jd_client::lib::downstream: Share do not meet downstream target`

Should probably be `Share does not meet downstream target` 

2. `2024-12-09T18:13:42.066868Z  WARN jd_client::lib::upstream_sv2::upstream: SNPH received from upstream, proxy ignore it, and use the one declared by JOB DECLARATOR

Should probably be `SNPH received from the upstream, proxy ignored it, and used the one declared by the JOB DECLARATOR CLIENT` `JOB DECLARATOR CLIENT` is probably what's needed here, I am unsure, a dev needs to confirm.

### PR DESCRIPTION
**Pull request by pavlenex**
motivated by #1280

good to have, but doesn't close the #1280 yet

### CODE REVIEW

File: roles/jd-client/src/lib/upstream_sv2/upstream.rs [hunk 1]
```diff
@@ -699,7 +699,7 @@ impl ParseUpstreamMiningMessages<Downstream, NullDownstreamMiningSelector, NoRou
         &mut self,
         _: roles_logic_sv2::mining_sv2::SetNewPrevHash,
     ) -> Result<roles_logic_sv2::handlers::mining::SendTo<Downstream>, RolesLogicError> {
-        warn!("SNPH received from upstream, proxy ignore it, and use the one declared by JOB DECLARATOR");
+        warn!("SNPH received from upstream, proxy ignored it, and used the one declared by JDC");
```
Comment (pavlenex) [inline roles/jd-client/src/lib/upstream_sv2/upstream.rs:702]: Someone needs to double check if it's JDC. JD seemed a bit generic, I tried to specify it.

**Review by plebhash — APPROVED** [review]
