### PR TITLE
`TemplateProvider` cleanup

### LINKED ISSUE #1368: `tests-integration::TemplateProvider` cleanup
- [ ] Move `download_bitcoind_tarball`, `unpack_tarball` and `read_tarball_from_file` outside of `template_provider.rs` file
 ~- [ ] Consider moving to async API, specificly `download_bitcoind_tarball(this is also a wrong name, this function performs http get request only)`~

- [ ] Document public functions

### PR DESCRIPTION
**Pull request by jbesraa**
resolves #1368

### CODE REVIEW

File: roles/tests-integration/lib/utils.rs [hunk 1]
```diff
@@ -28,3 +28,82 @@ fn get_available_port() -> u16 {
...
     }
 }
+
+pub mod http {
+    pub fn make_get_request(download_url: &str, retries: usize) -> Vec<u8> {
+        for attempt in 1..=retries {
+            let response = minreq::get(download_url).send();
+            match response {
+                Ok(res) => {
+                    if res.status_code >= 200 && res.status_code < 300 {
```
Comment (jbesraa) [inline roles/tests-integration/lib/utils.rs:38]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

**Comment by plebhash** [comment]
looks like clippy CI is breaking here

**Comment by plebhash** [comment]
https://github.com/stratum-mining/stratum/actions/runs/13241002338/job/36956174262?pr=1369#step:7:576

I am able to deterministically reproduce this locally

```
error[E0277]: `(TemplateProvider, std::net::SocketAddr)` is not a future
  --> tests-integration/tests/jd_integration.rs:27:56
   |
27 |     let (_tp, tp_addr) = start_template_provider(None).await;
   |                          ------------------------------^^^^^
   |                          |                            ||
   |                          |                            |`(TemplateProvider, std::net::SocketAddr)` is not a future
   |                          |                            help: remove the `.await`
   |                          this call returns `(TemplateProvider, std::net::SocketAddr)`
   |
   = help: the trait `Future` is not implemented for `(TemplateProvider, std::net::SocketAddr)`
   = note: (TemplateProvider, std::net::SocketAddr) must be a future or must implement `IntoFuture` to be awaited
   = note: required for `(TemplateProvider, std::net::SocketAddr)` to implement `IntoFuture`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `integration_tests_sv2` (test "jd_integration") due to previous error
warning: build failed, waiting for other jobs to finish...
```

**Review by plebhash — APPROVED** [review]

**Comment by jbesraa** [comment]
Rebased without further changes

**Comment by plebhash** [comment]
merging https://github.com/stratum-mining/stratum/pull/1430 introduced conflicts here

also clippy CI keeps breaking
