### PR TITLE
Sniffer fixes

### LINKED ISSUE #1384: Look into `Sniffer::recv_from_up_send_to_down` as it seems broken

### PR DESCRIPTION
**Pull request by jbesraa**
resolves #1384

### CODE REVIEW

File: roles/tests-integration/lib/sniffer.rs [hunk 1]
```diff
@@ -219,35 +219,35 @@ impl Sniffer {
...
-                            channel_msg,
-                        )
-                        .expect("Failed to create the frame"),
-                    );
-                    downstream_messages.add_message(
-                        intercept_message.replacement_message.message_type(),
+            let intercept_message = intercept_messages.iter().find(|im| {
+                im.direction == MessageDirection::ToDownstream
+                    && im.expected_message_type == msg_type
+            });
```
Comment (plebhash) [inline roles/tests-integration/lib/sniffer.rs:225]: I assume this was copy-pasted for both functions?

the direction here has to be `ToUpstream`

File: roles/tests-integration/lib/sniffer.rs [hunk 2]
```diff
@@ -256,30 +258,33 @@ impl Sniffer {
...
+                send.send(frame)
+                    .await
+                    .map_err(|_| SnifferError::DownstreamClosed)?;
             }
-            if send.send(frame).await.is_err() {
-                return Err(SnifferError::DownstreamClosed);
-            };
-            upstream_messages.add_message(msg_type, msg);
         }
         Err(SnifferError::UpstreamClosed)
```
Comment (plebhash) [inline roles/tests-integration/lib/sniffer.rs:289]: same here... shouldn't this be `DownstreamClosed`?

I'm not sure about the direction, but it definitely feels wrong to return the same error type for both functions

Comment (jbesraa) [reply roles/tests-integration/lib/sniffer.rs:288]: This is `recv_from_up_send_to_down`, if something fails while sending, it should return` DownstreamClosed` and if it fails when receiving it should return `UpstreamClosed`.  The incorrect appearance was at `recv_from_down_send_to_up`, which is fixed now.

**Review by plebhash — APPROVED** [review]
