### PR TITLE
fix mismatches in `channel_bit` and `message_type` according to the specs

### LINKED ISSUE #2094: `parsers_sv2` and subprotocols has some mismatches in `channel_bit` and `message_types`
if we look at the specs, we can see that the `Reconnect` message is a `common message`.

see https://github.com/stratum-mining/sv2-spec/blob/main/03-Protocol-Overview.md#365-reconnect-server---client

In our code we define it in `mining_sv2`:
https://github.com/stratum-mining/stratum/blob/ece2b035697ec35a8d1506ee1a321bccc9707b09/sv2/subprotocols/mining/src/lib.rs#L95

But it should be in `common_messages_sv2`

https://github.com/stratum-mining/stratum/blob/ece2b035697ec35a8d1506ee1a321bccc9707b09/sv2/subprotocols/common-messages/src/lib.rs#L46-L60

### PR DESCRIPTION
**Pull request by lucasbalieiro**
close #2094 

MAJOR BUMP `mining_sv2`.
MAJOR BUMP `job_declaration_sv2 `

### CODE REVIEW

**Comment by plebhash** [comment]
we'll have to bump `mining_sv2` MAJOR

~~and I THINK `common_messages_sv2` MINOR but could use a sanity check on this~~ #2073 already bumped `common_messages_sv2` MAJOR for the upcoming release

File: sv2/subprotocols/common-messages/src/lib.rs [hunk 1]
```diff
@@ -58,6 +58,7 @@ pub const CHANNEL_BIT_SETUP_CONNECTION: bool = false;
 pub const CHANNEL_BIT_SETUP_CONNECTION_SUCCESS: bool = false;
 pub const CHANNEL_BIT_SETUP_CONNECTION_ERROR: bool = false;
 pub const CHANNEL_BIT_CHANNEL_ENDPOINT_CHANGED: bool = true;
+pub const CHANNEL_BIT_RECONNECT: bool = false;
```
Comment (GitGab19) [inline sv2/subprotocols/common-messages/src/lib.rs:61]: Shouldn't we bump MINOR of `common_messages_sv2` for this?

File: sv2/parsers-sv2/src/lib.rs [hunk 2]
```diff
@@ -97,13 +98,12 @@ pub fn message_type_to_name(msg_type: u8) -> &'static str {
         0x1c => "SubmitSharesSuccess",
         0x1d => "SubmitSharesError",
         0x1f => "NewExtendedMiningJob",
-        0x20 => "SetNewPrevHash",
+        0x20 => "SetNewPrevHashMiningProtocol",
```
Comment (GitGab19) [inline sv2/parsers-sv2/src/lib.rs:101]: Why this change?

File: sv2/parsers-sv2/src/lib.rs [hunk 3]
```diff
@@ -116,9 +116,9 @@ pub fn message_type_to_name(msg_type: u8) -> &'static str {
         0x60 => "PushSolution",
 
         // Template Distribution messages (0x70-0x7F)
-        0x70 => "CoinbaseOutputDataSize",
+        0x70 => "CoinbaseOutputConstraints",
         0x71 => "NewTemplate",
-        0x72 => "SetNewPrevHash",
+        0x72 => "SetNewPrevHashTemplateDistributionProtocol",
```
Comment (GitGab19) [inline sv2/parsers-sv2/src/lib.rs:121]: Why this change?

File: sv2/subprotocols/common-messages/src/lib.rs (hunk 1 above)
Comment (lucasbalieiro) [reply sv2/subprotocols/common-messages/src/lib.rs:61]: CI did not complain about it and https://github.com/stratum-mining/stratum/pull/2073 already major bumped it

File: sv2/parsers-sv2/src/lib.rs (hunk 2 above)
Comment (lucasbalieiro) [reply sv2/parsers-sv2/src/lib.rs:101]: To make a clear distinction from `SetNewPrevHash` of the Template Distribution Protocol

File: sv2/parsers-sv2/src/lib.rs (hunk 3 above)
Comment (lucasbalieiro) [reply sv2/parsers-sv2/src/lib.rs:121]: To make a clear distincion of `SetNewPrevHash` from the Mining Protocol

File: sv2/subprotocols/job-declaration/src/lib.rs
Comment (plebhash) [inline sv2/subprotocols/job-declaration/src/lib.rs]:
```suggestion
// except for `PUSH_SOLUTION`, which requires a specific channel reference.
```

Comment (lucasbalieiro) [reply sv2/subprotocols/job-declaration/src/lib.rs]: thanks, done!
